### PR TITLE
TestSuiteAdapter changes

### LINKED ISSUE #5: Continue implementation of TestSuiteAdapter
### Context
`TestSuiteAdapter` is intended as a compatibility layer to bridge the gap between `GeneticAlgorithm<TestChromosome>` and `GeneticAlgorithm<TestSuiteChromosome>`. The main beneficiaries of this are the algorithms `MOSA`, `MIO` and `LIPS`. Up until now, many of the methods in `TestSuiteAdapter` are still left unimplemented, simply throwing an `UnsupportedOperationException("not implemented")` when being invoked. While all the methods relevant for `MOSA` should already be implemented, it is unclear whether this is also the case for `MIO` and `LIPS`.

### Expected result
Please check if an implementation of the following methods is necessary for `MOSA`, `MIO` or `LIPS` and give an appropriate implementation if possible (just tick the boxes once you're done):
- [x] `void evolve()` *
- [x] `void initializePopulation()` *
- [x] `void notifyMutation(TestSuiteChromosome chromosome)` *
- [x] `void notifyEvaluation(TestSuiteChromosome chromosome)` *
- [x] `boolean shouldApplyLocalSearch()`
- [x] `void disableFirstSecondaryCriterion()` *
- [x] `void enableFirstSecondaryCriterion()` *
- [x] `void updateSecondaryCriterion(int starvationCounter)` *
- [x] `void applyLocalSearch()`
- [x] `void updateProbability(boolean improvement)` *
- [x] `void generateInitialPopulation(int populationSize)` *
- [x] `void starveToLimit(int limit)` *
- [x] `void starveRandomly(int limit)` *
- [x] `void starveByFitness(int limit)` *
- [x] `void generateRandomPopulation(int populationSize)` *
- [x] `void clearPopulation()` *
- [x] `void addFitnessFunction(final FitnessFunction< TestSuiteChromosome> function)`
- [x] `FitnessFunction<TestSuiteChromosome> getFitnessFunction()` *
- [x] `int getNumberOfFitnessFunctions()` *
- [x] `SelectionFunction<TestSuiteChromosome> getSelectionFunction()` *
- [x] `RankingFunction<TestSuiteChromosome> getRankingFunction()` *
- [x] `void setRankingFunction(RankingFunction<TestSuiteChromosome> function)` *
- [x] `void setBloatControl(BloatControlFunction<TestSuiteChromosome> bcf)` *
- [x] `void addBloatControl(BloatControlFunction<TestSuiteChromosome> bloatControl)`
- [x] `boolean isTooLong(TestSuiteChromosome chromosome)` 
- [x] `void calculateFitness()`
- [x] `void calculateFitness(TestSuiteChromosome c)`
- [x] `void calculateFitnessAndSortPopulation()` *
- [x] `int getPopulationSize()` *
- [x] `List<TestSuiteChromosome> elitism()` *
- [x] `List<TestSuiteChromosome> randomism()` *
- [x] `void updateFitnessFunctionsAndValues()` *
- [x] `void writeIndividuals(List<TestSuiteChromosome> individuals)` *
- [x] `void removeListener(SearchListener<TestSuiteChromosome> listener)` 
- [x] `void sortPopulation()` *
- [x] `List<TestSuiteChromosome> getPopulation()`
- [x] `boolean isNextPopulationFull(List<TestSuiteChromosome> nextGeneration)` 
- [x] `boolean isFinished()`
- [x] `void setStoppingConditionLimit(int value)` *
- [x] `void updateBestIndividualFromArchive()` *
- [x] `boolean isBetterOrEqual(TestSuiteChromosome chromosome1, TestSuiteChromosome chromosome2)`
- [x] `void printBudget()` *
- [x] `String getBudgetString()` *
- [x] `double progress()` *

To this, one might simply run EvoSuite with the appropriate command line flags to enable `MOSA`, `MIO` and `LIPS` and observe whether EvoSuite currently crashes with an `UnsupportedOperationException`. If this is the case, one can simply look at the stack trace and identify the method that caused the exception. This method is one that still needs to be implemented.

### Contributing
Please push your changes to the branch [`5-continue-implementation-of-testsuite-adapter`](https://github.com/VoglSebastian/evosuite/tree/5-continue-implementation-of-testsuite-adapter)

### PR DESCRIPTION
**Pull request by VoglSebastian**
Implementation of some methods of TestSuiteAdapter.

Mostly i just redirected the method calls.

Additionally, adaptee algorithms notify the adapter now implicitly.

### CODE REVIEW

File: client/src/main/java/org/evosuite/ga/metaheuristics/TestSuiteAdapter.java [hunk 1]
```diff
@@ -312,28 +325,28 @@ final protected void calculateFitness(TestSuiteChromosome c)
...
-        throw new UnsupportedOperationException("not implemented");
+    final public int getPopulationSize() {
+        return algorithm.getPopulationSize();
     }
 
     @Override
-    final protected List<TestSuiteChromosome> elitism() throws UnsupportedOperationException {
-        throw new UnsupportedOperationException("not implemented");
+    final protected List<TestSuiteChromosome> elitism() {
+        return algorithm.elitism().stream().map(TestChromosome::toSuite).collect(toList());
```
Comment (schweikl) [inline client/src/main/java/org/evosuite/ga/metaheuristics/TestSuiteAdapter.java:336]: Question: this gives you a list of `TestSuiteChromosomes`, and every such chromosome contains exactly one test case, right? Wouldn't it make more sense to return a list containing just one `TestSuiteChromosome`, which in turn contains all the test cases? This approach seems to be more in line with `getBestIndividuals()` in `MOSATestSuiteAdapter`, `MIOTestSuiteAdapter` and `LIPSTestSuiteAdapter`. I suppose this would be easy to implement, too, since we already have a `TestChromosomeCollector`.

File: client/src/main/java/org/evosuite/ga/metaheuristics/TestSuiteAdapter.java [hunk 2]
```diff
@@ -312,28 +325,28 @@ final protected void calculateFitness(TestSuiteChromosome c)
...
     }
 
     @Override
-    final protected List<TestSuiteChromosome> randomism() throws UnsupportedOperationException {
-        throw new UnsupportedOperationException("not implemented");
+    final protected List<TestSuiteChromosome> randomism() {
+        return algorithm.randomism().stream().map(TestChromosome::toSuite).collect(Collectors.toList());
```
Comment (schweikl) [inline client/src/main/java/org/evosuite/ga/metaheuristics/TestSuiteAdapter.java:341]: Here, we have to ask ourselves the same question as for `elitism()` (see above). In any case, whatever the outcome will be, we have to make sure that we handle `elitism()` and `randomism()` consistently.

File: client/src/main/java/org/evosuite/ga/metaheuristics/TestSuiteAdapter.java [hunk 3]
```diff
@@ -434,13 +447,14 @@ final public void notifyIteration() { // called by the adaptee
...
-    final protected void sortPopulation() throws UnsupportedOperationException {
-        throw new UnsupportedOperationException("not implemented");
+    final protected void sortPopulation() {
+        algorithm.sortPopulation();
     }
 
     @Override
     final public List<TestSuiteChromosome> getPopulation() throws UnsupportedOperationException {
-        throw new UnsupportedOperationException("not implemented");
+        // The documentation of GeneticAlgorithm::getPopulation states, that an accessor to the population is returned.
```
Comment (schweikl) [inline client/src/main/java/org/evosuite/ga/metaheuristics/TestSuiteAdapter.java]: Just to clarify: we could (in principle) implement `getPopulation()` as follows:
```Java
final public List<TestSuiteChromosome> getPopulation() 
    return Collections.singletonList(algorithm.getPopulation().stream().collect(TestChromosome.toTestSuiteCollector));
}
```
But this solution was not chosen because it violates the contract described in the JavaDoc of `GeneticAlgorithm::getPopulation`:

> `Accessor for population Chromosome`

To me, the JavaDoc is ambiguous. Does it really state that we must return a reference to the actual population and that we can't return a reference to (some) copy of the population?

**Review by schweikl — COMMENTED** [review]
Hi, I have finished my review of your changes and left some notes/comments which we should probably discuss before we merge this. It's just minor things here and there, most of the changes look good to me.

File: client/src/main/java/org/evosuite/ga/metaheuristics/TestSuiteAdapter.java (hunk 3 above)
Comment (VoglSebastian) [reply client/src/main/java/org/evosuite/ga/metaheuristics/TestSuiteAdapter.java]: I understood the JavaDoc, that i can add/delete elements by editing the population:

e.g.
`ga.getPopulation().clear(); `

would clear the population of ga.
I was concerned, that some code will break, if the population can not be accessed by getPopulation().

I looked at the usages of getPopulation() and have not found a case, where the Population is edited with the accessor.
Considering this, i would recommend, that we use your proposed Implementation of the function.

Maybe we should edit the JavaDoc of getPopulation() in GeneticAlgorithm aswell and return a copy of the population?

File: client/src/main/java/org/evosuite/ga/metaheuristics/TestSuiteAdapter.java (hunk 1 above)
Comment (VoglSebastian) [reply client/src/main/java/org/evosuite/ga/metaheuristics/TestSuiteAdapter.java:336]: I think both approaches are fine.

I went with the List of test suites, because before the refactoring, this function would have returned a list of tests.

If you think we should return a List only containing one test suite, i am fine with it.

File: client/src/main/java/org/evosuite/ga/metaheuristics/TestSuiteAdapter.java (hunk 3 above)
Comment (schweikl) [reply client/src/main/java/org/evosuite/ga/metaheuristics/TestSuiteAdapter.java]: >  Considering this, i would recommend, that we use your proposed Implementation of the function.

Great :+1: Could you update the changes in your PR in that respect?

> Maybe we should edit the JavaDoc of getPopulation() in GeneticAlgorithm aswell and return a copy of the population?

I think we should. Your comment made me aware that the current implementation of `getPopulation()`
```Java
  public List<T> getPopulation() {
        return population;
    }
```
breaks encapsulation :frowning: And I agree with you, this is bad and we should fix this since it allows callers to mess with the `GeneticAlgorithm`'s internal state. But instead of returning a copy maybe it also suffices to do this?
```Java
 public List<T> getPopulation() {
        return Collections.unmodifiableList(population);
    }
```
When someone tries to add or delete chromosomes from the returned list they would get an `UnsupportedOperationException` exception. This would be fine for me. Returning a copy of the list would allow callers to modify the list, with which I am also fine since it doesn't affect the internal state of the GA either.

File: client/src/main/java/org/evosuite/ga/metaheuristics/TestSuiteAdapter.java (hunk 1 above)
Comment (schweikl) [reply client/src/main/java/org/evosuite/ga/metaheuristics/TestSuiteAdapter.java:336]: OK, then let's keep your implementation :smile:

File: client/src/main/java/org/evosuite/ga/metaheuristics/TestSuiteAdapter.java (hunk 2 above)
Comment (schweikl) [reply client/src/main/java/org/evosuite/ga/metaheuristics/TestSuiteAdapter.java:341]: Since it has just been decided to keep your implementation of `elitism()` we keep it here as well

File: client/src/main/java/org/evosuite/ga/metaheuristics/TestSuiteAdapter.java (hunk 3 above)
Comment (schweikl) [reply client/src/main/java/org/evosuite/ga/metaheuristics/TestSuiteAdapter.java]: I think 50c7bae resolves this conversation.

**Review by schweikl — APPROVED** [review]
LGTM
